### ISSUE TITLE
CreateImage2D obsolete/deprecated?

### ISSUE THREAD

**Issue by Stevie-O** [clSharp/Cloo#15]
The code marks the CreateImage2D constructor as obsolete, simply saying it is "deprecated" without explaining what to use instead (rather poor form, really).

It would seem that OpenCL v1.2 deprecates clCreateImage2D and clCreateImage3D in favor of clCreateImage, but there does not seem to be a way to invoke clCreateImage from the current version of Cloo.

**Comment by clSharp** [comment]
The original Cloo project was not updated since 2012. In 2015 I forked it, because I had to fix some bugs and add some functionality. I will only fix/add things I need myself as I do not have the time to extensively maintain this project.

If you think anything is "rather poor form, really" feel free to change it here or in your own branch. If you send a merge request I will check and merge it.

You will find a lot of documentation from Khronos (including deprecated functions). As most things in this project are very close to the original API I think it's not necessary to double too much of it here.
